{'blocks': [{'type': 'radio',
             'units': [[None,
                        [{'label': 'A question goes here...',
                          'type': 'MultiLineTextInputUnit'}],
                        None,
                        None],
                       [[{'label': 'option 1',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 2',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 3',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 4',
                          'type': 'SingleLineTextInputUnit'}]]]},
            {'type': 'radio',
             'units': [[None,
                        [{'label': 'A question goes here...',
                          'type': 'MultiLineTextInputUnit'}],
                        None,
                        None],
                       [[{'label': 'option 1',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 2',
                          'type': 'SingleLineTextInputUnit'}]]]},
            {'type': 'section',
             'units': [[None,
                        [{'label': 'Title of this section...',
                          'type': 'SingleLineTextInputUnit'}]],
                       []]},
            {'type': 'radio',
             'units': [[None,
                        [{'label': 'A question goes here...',
                          'type': 'MultiLineTextInputUnit'}],
                        None,
                        None],
                       [[{'label': 'option 1',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 2',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 3',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 4',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 5',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 6',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 7',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 8',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 9',
                          'type': 'SingleLineTextInputUnit'}]]]},
            {'type': 'question',
             'units': [[None,
                        [{'label': 'A question goes here...',
                          'type': 'MultiLineTextInputUnit'}]],
                       []]}],
 'formId': 4,
 'lang': 'hu',
 'title': 'untitled'}
