{'blocks': [{'type': 'section',
             'units': [None,
                       [{'label': 'ez egy szekció',
                         'type': 'SingleLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'mi a kérdés?',
                         'type': 'MultiLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'nekem kell válaszolni?',
                         'type': 'MultiLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'ez egy új kérdés...?',
                         'type': 'MultiLineTextInputUnit'}]]}],
 'formId': 1,
 'lang': 'hu',
 'title': 'szia világ ez egy update'}
