{'blocks': [{'type': 'radio',
             'units': [[None,
                        [{'label': 'A question goes here...',
                          'type': 'MultiLineTextInputUnit'}],
                        None,
                        None],
                       [[{'label': 'option 1',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 2',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 3',
                          'type': 'SingleLineTextInputUnit'}],
                        [{'label': 'option 4',
                          'type': 'SingleLineTextInputUnit'}]]]}],
 'formId': 3,
 'lang': 'hu',
 'title': 'untitled'}
