{'blocks': [{'type': 'section',
             'units': [None,
                       [{'label': 'some title',
                         'type': 'SingleLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'hey hey hey',
                         'type': 'MultiLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'a new world',
                         'type': 'MultiLineTextInputUnit'}]]},
            {'type': 'section',
             'units': [None,
                       [{'label': 'a label here!',
                         'type': 'SingleLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'and the question :)',
                         'type': 'MultiLineTextInputUnit'}]]},
            {'type': 'section',
             'units': [None,
                       [{'label': 'fuck yeah',
                         'type': 'SingleLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'this is it :)',
                         'type': 'MultiLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'no it is not',
                         'type': 'MultiLineTextInputUnit'}]]},
            {'type': 'question',
             'units': [None,
                       [{'label': 'etc etc.',
                         'type': 'MultiLineTextInputUnit'}]]}],
 'lang': 'en',
 'title': 'hello world'}
